### ISSUE TITLE
BUG  LaunchActivity 的生命周期无法执行

### ISSUE THREAD

**Issue by fangding** [18598925736/HookSkinDemoFromHank#1]
发现一个致命的bug：hook之后，LaunchActivity 的生命周期完全无法执行了，例如：onRestar、onResume、onPause、onStop 等等

**Comment by 13217300237** [comment]
谢谢，我有空看看再回复你




------------------ 原始邮件 ------------------
发件人: "fangding"<notifications@github.com>;
发送时间: 2019年5月17日(星期五) 上午10:12
收件人: "18598925736/HookSkinDemoFromHank"<HookSkinDemoFromHank@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [18598925736/HookSkinDemoFromHank] BUG  LaunchActivity 的生命周期无法执行 (#1)




发现一个致命的bug：hook之后，LaunchActivity 的生命周期完全无法执行了，例如：onRestar、onResume、onPause、onStop 等等
